{
 "title": "API Manager",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"}",
     "legendFormat": "{{ instance }}{{ handler }} status:{{status}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"api\", handler!~\"/docs|/metrics|none|/openapi.json\"}[1m])",
     "legendFormat": "{{ method }}  {{ instance }}{{ handler }} {{ status }}"
    }
   ]
  },
  {
   "title": "Request per min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"}[1m])",
     "legendFormat": "{{ instance }}{{ handler }} status:{{ status }}"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"}[1m])",
     "legendFormat": "{{ instance }}{{ handler }} status:{{status}}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status!=\"2xx\"}[1m]))",
     "legendFormat": "errors {{ handler }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"} / http_request_duration_seconds_count{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"}",
     "legendFormat": "{{ instance }}{{ handler }}"
    }
   ]
  },
  {
   "title": "Average Response TIme [Last 5m]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"}[5m]) / rate(http_request_duration_seconds_count{job=\"api\", handler!~\"/docs|/metrics|/openapi.json|none\"}[5m])",
     "legendFormat": "{{ instance }}{{ handler }}"
    }
   ]
  }
 ]
}